### ISSUE TITLE
double dashes in the beginning of content will nuke the file intended to be created

### ISSUE THREAD

**Issue by wong604** [southalc/types#3]
types::file:
  /tmp/testfile:
    ensure: file
    content: |
      --testing

The above code will create a nuke file /tmp/testfile. However, the following code will create a file with the content 'testing':
types::file:
  /tmp/testfile:
    ensure: file
    content: |
      testing

This only happen in Puppet Enterprise, but not satellite. However, I cannot recreate the problem with the following .pp code:
file { '/tmp/testfile':
  content      => '--testing',
}

It will create a file with --testing as its content, even though there is no newline at the end of the file.

The following code will also create a null file:
types::file:
  /tmp/testfile:
    ensure: file
    content: '--testing'

The following code will do the same thing:
types::file:
  /tmp/testfile:
    ensure: file
    mode: '0444'
    owner: 'root'
    group: 'root'
    content: |
      -%{'nullvar'}-testing

Is there a workaround? Can you specify it in hex?

**Comment by wong604** [comment]
Cannot find anything in particular. If I use:
stdlib::manage::create_resources:
  file:
    /etc/somefile:
      ensure: file
      owner: root
      group: root
      content: |
        %{'var_that_does_not_exist'}----testing----

/etc/somefile will be created with '----testing----'

However, types::files: will still create a null file.

Thanks,

Joseph Wong, Enterprise Systems Administrator
P: 604-215-4820 / C: 604-218-2052
ecomm911.ca<https://www.ecomm911.ca/> @EComm911_info<https://twitter.com/ecomm911_info>
CONFIDENTIALITY NOTICE: This email and any attachments are only for the use of the intended recipient and must not be distributed, disclosed, used or copied by or to anyone else. This transmission may contain confidential or privileged information, and the sender does not waive any related rights, protection or obligations in connection with such materials. The unauthorized use or disclosure of this material may be unlawful and result in legal action or other sanctions. If you have received this email in error please immediately contact the sender by return email and delete all copies of this email and any attachments.

**Comment by wong604** [comment]
BTW. May be I should upgrade my puppet enterprise:
It is:
rpm -qa|grep puppe
pe-puppet-enterprise-release-2021.5.0.2-2.pe.el8.noarch
puppet-agent-7.14.0-1.el8.x86_64
pe-puppetdb-termini-7.9.2-1.el8.noarch
pe-puppetserver-2021.5.0.23-1.el8.noarch
pe-puppetdb-7.9.2-1.el8.noarch


Joseph Wong, Enterprise Systems Administrator
P: 604-215-4820 / C: 604-218-2052
ecomm911.ca<https://www.ecomm911.ca/> @EComm911_info<https://twitter.com/ecomm911_info>
CONFIDENTIALITY NOTICE: This email and any attachments are only for the use of the intended recipient and must not be distributed, disclosed, used or copied by or to anyone else. This transmission may contain confidential or privileged information, and the sender does not waive any related rights, protection or obligations in connection with such materials. The unauthorized use or disclosure of this material may be unlawful and result in legal action or other sanctions. If you have received this email in error please immediately contact the sender by return email and delete all copies of this email and any attachments.

**Comment by southalc** [comment]
Unable to reproduce the problem.
