### ISSUE TITLE
Some types provided by modules ignored

### ISSUE THREAD

**Issue by parryb** [southalc/types#4]
Hello,

I'm running Opensource Puppet Server 7.4.2 and Puppet clients 7.16 on RHEL 8.6

I'm loading a bunch of modules like puppet-archive and puppet-rhsm.  They provide some types (archive and rh_repo)  I have defined calling them in hiera like so;

types::archive:
  /tmp/somezipfile.zip:
   ensure: 'present'

Yet they get completely ignored no error messages nothing.  Yet other types such as puppetlabs-stdlib which provides file_line work perfectly well using the same format.  I can't figure out how why this is?  Since the type work if I put them in a puppet manifest and call that as class I figure it must be an issue with types not picking up the declaration?

**Comment by parryb** [comment]
I've also ensured that it generates a hiera hash using puppet lookup

**Comment by southalc** [comment]
I attempt to explain this in the documentation, but maybe it isn't clear: "Support for new types is enabled by using the types parameter with an array of additional types."  This means the "types" module also has a parameter named "types".  You can declare this in hiera.  For example, to add the archive type you need:
```
types::types:
  - 'archive'
```
You can add any type of defined type this way.  The example from the module docs show this for the concat_file and concat_fragment types:
https://github.com/southalc/types#examples

**Comment by parryb** [comment]
Yeah I just figured that out sorry! Fault lay between screen and chair. sorry to waste your time
