### ISSUE TITLE
Template function call on file resource

### ISSUE THREAD

**Issue by parryb** [southalc/types#5]
I'm bashing my head against a wall trying to get a template function to work on a file resource using types module.  I am running Open Source Puppet 7.9 as part of Satellite 6.13.  My heira code is;

types::file:
  /path/to/my/file:
    ensure: present
    owner: root
    content: template('mymodule/myfile.erb')

The generated file does not contain myfile.erb instead it contains the string; "template('mymodule/myfile.erb')"

**Comment by southalc** [comment]
Sorry, but the "template" keyword is a function name and the only function you can call directly in hiera is "lookup".  If the file template isn't too complex, you could put the template content into hiera as a YAML block and substitute your values with lookup calls directly.  For example:
```
# These values stored in common site hiera data
dns_domain: "example.com"
dns_server1: "dns1.example.com"

# Use lookup to reference other hiera values
types::file:
  /etc/resolv.conf:
    ensure: file
    content: |
      # FILE MANAGED BY PUPPET
      search %{lookup('dns_domain')}
      nameserver %{lookup('dns_server1')}
```
